### ISSUE TITLE
Pytorch environment conflict

### ISSUE THREAD

**Issue by haobo724** [daooshee/QuadPrior#4]
Firstly, thank you for this impressive paper and code.

However, when I first used the guide to initialise the environment, I had problems showing 
 ```
 torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available
```
My PC environment:

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Thu_Nov_18_09:45:30_PST_2021
Cuda compilation tools, release 11.5, V11.5.119
Build cuda_11.5.r11.5/compiler.30672275_0
Platform: windows-wsl

But I solved the problem by upgrading pytorch to the latest version (till now is ) and using pip instead of conda.

So I am not that sure it is a unique conflict or is it universal.  But I think modifying the _environment. yaml_ file is still worth a try.

**Comment by daooshee** [comment]
Thank you for sharing this problem and your experience of how to fix it!
The `environment.yaml` works well on my Ubuntu server. And since I don't have a Windows machine with GPU, I cannot reproduce this issue.
I set the pytorch version to 1.12.1 because `pytorch-lightning` and `transformers` change much in different versions. I don't know when upgrading to the newest pytorch version, whether these packages will be upgraded too and cause new issues or not. If you face new issues, maybe you can reinstall `torch==1.12.1` by pip according to https://pytorch.org/get-started/previous-versions/.
I'll also mark the problem in README. Thank you again for sharing this problem.

**Comment by haobo724** [comment]
> Thank you for sharing this problem and your experience of how to fix it! The `environment.yaml` works well on my Ubuntu server. And since I don't have a Windows machine with GPU, I cannot reproduce this issue. I set the pytorch version to 1.12.1 because `pytorch-lightning` and `transformers` change much in different versions. I don't know when upgrading to the newest pytorch version, whether these packages will be upgraded too and cause new issues or not. If you face new issues, maybe you can reinstall `torch==1.12.1` by pip according to https://pytorch.org/get-started/previous-versions/. I'll also mark the problem in README. Thank you again for sharing this problem.

Thank you for reply! Actually  windows-wsl is Linux (Ubuntu) environment.  I understand your concern that dependency conflicts are always annoying. In my case I just need to upgrade the pytorch and it works. 

Thanks again for your work, and if someone asks a similar dependency question in the future you can refer t to this issue :)
